FileVersion = 1
Projects = {tecs = {Path = "."}}

[Workspace]
StartupProject = "tecs"

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false

[Configs.Release.Win64]
BfOptimizationLevel = "O3"
EmitDebugInfo = "No"

[Configs.Release.wasm32]
BfOptimizationLevel = "O3"
EmitDebugInfo = "No"
